---
http_interactions:
- request:
    method: post
    uri: http://localhost:5781/api/v1/logs
    body:
      encoding: UTF-8
      string: "{\"log\":{\"source_name\":\"test\",\"source_created_at\":\"2014-08-25T08:35:22.730-05:00\",\"level\":3,\"external_parent_id\":33,\"external_parent_source_name\":\"g5-jobs\",\"title\":\"test
        title\",\"message\":\"a big error occurred\"}}"
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Content-Type:
      - application/json
      Accept:
      - application/json
  response:
    status:
      code: 201
      message: 'Created '
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - "\"a5153195873ed0bb404473096addaf3c\""
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - f5e8ebfc-dea5-42b7-8294-712470a9584e
      X-Runtime:
      - '0.008999'
      Server:
      - WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)
      Date:
      - Mon, 25 Aug 2014 13:35:22 GMT
      Content-Length:
      - '154'
      Connection:
      - Keep-Alive
    body:
      encoding: UTF-8
      string: "{\"log\":{\"id\":22,\"title\":\"test title\",\"source_name\":\"test\",\"level\":3,\"external_parent_id\":33,\"external_parent_source_name\":\"g5-jobs\",\"attachment_urls\":[]}}"
    http_version: 
  recorded_at: Mon, 25 Aug 2014 13:35:22 GMT
recorded_with: VCR 2.9.2
